default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: 'sergey'
  password:

development:
  <<: *default
  database: my_car_expenses_development

test:
  <<: *default
  database: my_car_expenses_test

production:
  <<: *default
  database: my_car_expenses_production
